[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "development-tools", "embedded"]
description = "Flips the memory layout of embedded programs to protect against stack overflows"
edition = "2018"
keywords = ["arm", "cortex-m", "stack-protection"]
license = "MIT OR Apache-2.0"
name = "flip-link"
repository = "https://github.com/knurling-rs/flip-link"
version = "0.1.4"
readme = "README.md"

[dependencies]
anyhow = "1.0"
env_logger = { version = "0.8", default-features = false }
log = "0.4"
object = { version = "0.25", default-features = false, features = ["read_core", "elf", "std"] }
getrandom = "0.2"

[dev-dependencies]
assert_cmd = "1.0"
rstest = "0.10"

[workspace]
members = [".", "xtest"]
