[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "development-tools", "embedded"]
description = "Flips the memory layout of embedded programs to protect against stack overflows"
edition = "2018"
keywords = ["arm", "cortex-m", "stack-protection"]
license = "MIT OR Apache-2.0"
name = "flip-link"
repository = "https://github.com/knurling-rs/flip-link"
version = "0.1.2"
readme = "README.md"

[dependencies]
anyhow = "1.0.32"
env_logger = "0.8.3"
log = "0.4.11"
object = "0.23.0"
structopt = "0.3.21"
tempfile = "3.1.0"
